import { useRouter } from 'next/navigation';
import { useEffect } from 'react';
// import Head from 'next/head';

import { getAccount } from '@nx-expo/appwrite';

const getData = async () => {
  const res = await fetch('http://localhost:4200/api/account');
  const { user } = await res.json();
  console.log('getting data user: ', user);
  return user;
};

// export const metadata = {
//   title: 'Nx Next App',
//   description: 'Generated by create-nx-workspace',
// };

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getData();
  console.log('user: ', user);

  return (
    <html lang="en">
      {/* <Head>
        <title>Welcome to admin-panel!</title>
      </Head> */}
      <body>{children}</body>
    </html>
  );
}
